#pragma once

#define FORCE_NKRO

#define RGB_DISABLE_TIMEOUT 600000                  // 10 Mins
#define RGB_DISABLE_WHEN_USB_SUSPENDED true
#define RGB_MATRIX_MAXIMUM_BRIGHTNESS  255
#define RGB_MATRIX_STARTUP_MODE RGB_MATRIX_RAINBOW_MOVING_CHEVRON
#define RGB_MATRIX_STARTUP_VAL RGB_MATRIX_MAXIMUM_BRIGHTNESS
#define RGB_MATRIX_STARTUP_SPD 119                  // Default is 127
#define RGB_MATRIX_VAL_STEP 17                      // Default is 16
#define RGB_MATRIX_SPD_STEP RGB_MATRIX_VAL_STEP     // Default is 16

#define MK_3_SPEED
#define MK_C_OFFSET_UNMOD 1
#define MK_C_INTERVAL_UNMOD 16
